package controller;

public enum Actions {
	MAIN_USERS_BUTTON, MAIN_PRODUCTS_BUTTON, MAIN_REPORTS_BUTTON, MAIN_EXPENDITURES_BUTTON,
	MAIN_SELL_BUTTON, ADD_USER_BUTTON, BACK_BUTTON, DONE_ADD_USER_BUTTON, 
	CANCEL_ADD_USER_BUTTON, ADD_PRODUCT_BUTTON, DONE_ADD_PRODUCT_BUTTON, 
	CANCEL_ADD_PRODUCT_BUTTON, ADD_ITEM_BUTTON, DONE_ADD_ITEM_BUTTON, CANCEL_ADD_ITEM_BUTTON, 
	ADD_ITEM_TO_CAR, CONFIRM_SELL_BUTTON, REMOVE_PRODUCT_FROM_SELL, EDIT_USER_BUTTON, 
	EDIT_PRODUCT_BUTTON, DONE_EDIT_USER_BUTTON, DONE_EDIT_PRODUCT_BUTTON, 
	ADD_EXPENDITURE_BUTTON, DONE_ADD_EXPENDITURE_BUTTON, CANCEL_ADD_EXPENDITURE_BUTTON, 
	LOGIN_BUTTON, LOGIN_CANCEL_BUTTON, DELETE_USER_BUTTON;
}
